- name: Download Wordpress.org
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract .tar.gz file
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no
  
- name: Set configuration of available sites
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: '(.)+DocumentRoot /var/www/html'
    line: 'DocumentRoot /var/www/html/wordpress'

- name: Update Apache global settings
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '<Directory /var/www/>'
    line: '<Directory /var/www/html/>'
  notify:
    - restart apache

- name: Copy Wordpress config sample
  command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php

- name: Set Wordpress global settings
  lineinfile:
    dest=/var/www/html/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{mysql_db}}' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{mysql_user}}' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{mysql_password}}' );"}
    - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', '{{mysql_host}}' );"}

